# Generated by Django 5.2.8 on 2025-12-25 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='id',
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnerid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
