# Generated by Django 5.2.8 on 2026-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_partner_contact_person_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('purchasing', 'Purchasing'), ('inventory', 'Inventory'), ('logistics', 'Logistics'), ('store', 'Store'), ('accounting', 'Accounting')], default='logistics', max_length=20),
        ),
    ]
