# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_accounting_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('purchasing', 'Purchasing'), ('inventory', 'Inventory'), ('logistics', 'Logistics'), ('store', 'Store'), ('accounting', 'Accounting'), ('transitor', 'Transitor')], default='logistics', max_length=20),
        ),
    ]
