# Generated by Django 5.2.8 on 2025-12-04 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('grn_no', models.CharField(max_length=255)),
                ('plate_no', models.CharField(max_length=255)),
                ('purchase_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrnItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_measurement', models.CharField(max_length=100)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.grn')),
            ],
        ),
    ]
