# Generated by Django 5.2.8 on 2025-12-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnitems',
            name='internal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
