# Generated by Django 5.2.8 on 2025-12-04 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_grnitems_internal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('dn_no', models.CharField(max_length=255, unique=True)),
                ('plate_no', models.CharField(max_length=255)),
                ('sales_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DNItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_measurement', models.CharField(max_length=100)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dn_items', to='inventory.dn')),
            ],
        ),
    ]
