# Generated by Django 5.2.8 on 2025-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_dn_dnitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='dn',
            name='ECD_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='storekeeper_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dnitems',
            name='bags',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='ECD_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='storekeeper_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grnitems',
            name='bags',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
