# Generated by Django 5.2.8 on 2025-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_dn_ecd_no_dn_date_dn_storekeeper_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dn',
            old_name='storekeeper_name',
            new_name='authorized_by',
        ),
        migrations.RenameField(
            model_name='dn',
            old_name='transporter_name',
            new_name='despathcher_name',
        ),
        migrations.AddField(
            model_name='dn',
            name='gatepass_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dn',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
