# Generated by Django 5.2.8 on 2025-12-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_storekeeper_name_dn_authorized_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('hscode', models.CharField(max_length=255)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('hscode', models.CharField(max_length=255)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, max_length=100, null=True)),
                ('unit_measurement', models.CharField(max_length=100)),
                ('package', models.FloatField(blank=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
