# Generated by Django 5.2.8 on 2026-01-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_items_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grn',
            options={'ordering': ['grn_no']},
        ),
        migrations.AlterModelOptions(
            name='grnitems',
            options={'ordering': ['grn']},
        ),
    ]
