# Generated by Django 5.2.8 on 2026-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_grn_options_alter_grnitems_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='grn_no',
            field=models.IntegerField(max_length=255),
        ),
    ]
