# Generated by Django 5.2.8 on 2026-01-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_grn_grn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='grn_no',
            field=models.IntegerField(unique=True),
        ),
    ]
