# Generated by Django 5.2.8 on 2026-03-09 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_grn_grn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('proforma_ref_no', models.CharField(max_length=255)),
                ('buyer', models.CharField(max_length=255)),
                ('add_consignee', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField()),
                ('shipper', models.CharField(max_length=255)),
                ('notify_party', models.CharField(blank=True, max_length=255, null=True)),
                ('add_notify_party', models.CharField(blank=True, max_length=255, null=True)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('final_destination', models.CharField(max_length=255)),
                ('port_of_loading', models.CharField(max_length=255)),
                ('port_of_discharge', models.CharField(max_length=255)),
                ('measurement_type', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=100)),
                ('mode_of_transport', models.CharField(max_length=50)),
                ('freight', models.CharField(max_length=50)),
                ('freight_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipment_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('hs_code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('measurement', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order')),
            ],
        ),
    ]
