# Generated by Django 5.2.8 on 2026-03-09 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_order_approved_by_purchase_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('invoice_date', models.DateField()),
                ('waybill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_order_number', models.CharField(max_length=255)),
                ('container_number', models.CharField(blank=True, max_length=255, null=True)),
                ('vessel', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_remark', models.TextField(blank=True, null=True)),
                ('packing_list_remark', models.TextField(blank=True, null=True)),
                ('waybill_remark', models.TextField(blank=True, null=True)),
                ('bill_of_lading_remark', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_invoices', to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('measurement', models.CharField(max_length=100)),
                ('bags', models.FloatField(blank=True, null=True)),
                ('net_weight', models.FloatField(blank=True, null=True)),
                ('gross_weight', models.FloatField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.shippinginvoice')),
            ],
        ),
    ]
