# Generated by Django 5.2.8 on 2026-03-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_shippinginvoiceitem_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='plate_no',
        ),
        migrations.AddField(
            model_name='grn',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inventory.purchase'),
        ),
        migrations.AddField(
            model_name='grn',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grn',
            name='truck_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
