# Generated by Django 5.2.8 on 2026-03-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_grn_plate_no_grn_purchase_grn_received_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='purchase',
        ),
    ]
