# Generated by Django 5.2.8 on 2026-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_grn_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='storekeeper_name',
        ),
        migrations.AddField(
            model_name='purchase',
            name='before_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
