# Generated by Django 5.2.8 on 2026-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_shippinginvoiceitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='before_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
