# Generated by Django 5.2.8 on 2026-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_reset_grnitems_dnitems_id_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnitems',
            name='catalog_item_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
