# Generated by Django 5.2.8 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0043_dnitems_catalog_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="remaining",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_quantity",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="shippinginvoiceitem",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
