# Generated by Django 5.2.8 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0044_order_and_shipping_item_quantity_float"),
    ]

    operations = [
        migrations.AddField(
            model_name="grnitems",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="dnitems",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]

