# Generated by Django 5.2.8 on 2026-04-07 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0045_add_code_to_grnitems_dnitems"),
    ]

    operations = [
        migrations.CreateModel(
            name="GIT",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("purchase_no", models.CharField(db_index=True, max_length=255)),
                ("item_name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ("purchase_quantity", models.FloatField(default=0)),
                ("received_quantity", models.FloatField(default=0)),
                ("variance_quantity", models.FloatField(default=0)),
                ("variance_type", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grn", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="git_rows", to="inventory.grn")),
            ],
        ),
    ]

