# Generated by Django 5.2.8 on 2026-08-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_alter_marineinsurance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marineinsurance',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
