# Generated by Django 5.0.7 on 2026-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_alter_marineinsurance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginvoice',
            name='destination_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shippinginvoice',
            name='destination_contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
