# Generated by Django 5.0.7 on 2026-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_alter_marineinsurance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shippinginvoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
