# Generated by Django 5.0.7 on 2026-08-28 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_shippinginvoiceitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseReleaseNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('wrn_no', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'wrn_no'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wsn_no', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.FloatField()),
                ('unit_measurement', models.CharField(max_length=100)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bags', models.FloatField(blank=True, null=True)),
                ('remaining_quantity', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['storage_note'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorageNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('wsn_no', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('ECD_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('storage_period_value', models.PositiveIntegerField(default=1)),
                ('storage_period_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='months', max_length=10)),
                ('storage_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grace_period_value', models.PositiveIntegerField(default=0)),
                ('grace_period_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='days', max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'wsn_no'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wrn_no', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('item_name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('quantity', models.FloatField()),
                ('unit_measurement', models.CharField(max_length=100)),
                ('internal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bags', models.FloatField(blank=True, null=True)),
                ('release_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousereleasenote')),
                ('storage_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_items', to='inventory.warehousestorageitem')),
            ],
            options={
                'ordering': ['release_note'],
            },
        ),
        migrations.AddField(
            model_name='warehousestorageitem',
            name='storage_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousestoragenote'),
        ),
        migrations.AddField(
            model_name='warehousereleasenote',
            name='storage_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_notes', to='inventory.warehousestoragenote'),
        ),
        migrations.CreateModel(
            name='ExpirationFeeTier',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('tier_index', models.PositiveIntegerField()),
                ('period_value', models.PositiveIntegerField(default=1)),
                ('period_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='months', max_length=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('storage_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_fee_tiers', to='inventory.warehousestoragenote')),
            ],
            options={
                'ordering': ['tier_index'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorageTopUp',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('top_up_date', models.DateField()),
                ('additional_period_value', models.PositiveIntegerField()),
                ('additional_period_unit', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months')], default='months', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.TextField(blank=True, null=True)),
                ('storage_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='inventory.warehousestoragenote')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expirationfeetier',
            constraint=models.UniqueConstraint(fields=('storage_note', 'tier_index'), name='uniq_exp_fee_storage_tier'),
        ),
    ]
