# Generated by Django 5.0.7 on 2026-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_warehousereleasenote_warehousestorageitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestoragenote',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousestoragenote',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousestoragenote',
            name='last_notified_tier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
