# Generated by Django 5.0.7 on 2026-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_merge_0039_0063'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginvoice',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
