# Generated by Django 5.0.7 on 2026-10-09 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_shippinginvoice_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='assigned_transitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stage',
            field=models.CharField(blank=True, choices=[('ecd_im8', 'ECD / IM8'), ('transit_permit', 'Transit Permit'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stage_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stage_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
