# Generated by Django 5.0.7 on 2026-09-04 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_warehousestoragenote_expiry_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestoragenote',
            name='price_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousestoragenote',
            name='price_entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_storage_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WarehouseStorageEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entry_date', models.DateField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='inventory.warehousestoragenote')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorageEntryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.FloatField()),
                ('bags', models.FloatField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehousestorageentry')),
                ('storage_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_items', to='inventory.warehousestorageitem')),
            ],
        ),
    ]
