# Generated by Django 5.2.8 on 2026-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_purchase_assigned_transitor_purchase_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ecd_file',
            field=models.FileField(blank=True, help_text='ECD / IM8 document (required to enter the ECD / IM8 checkpoint).', null=True, upload_to='purchases/ecd/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transit_permit_file',
            field=models.FileField(blank=True, help_text='Transit permit document (optional).', null=True, upload_to='purchases/transit_permit/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stage',
            field=models.CharField(blank=True, choices=[('ecd_im8', 'ECD / IM8'), ('transit_permit', 'Transit Permit'), ('closure_guarantee', 'Closure Guarantee'), ('done', 'Done'), ('cancelled', 'Cancelled')], default=None, max_length=20, null=True),
        ),
    ]
