# Generated by Django 5.2.8 on 2026-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_purchase_ecd_file_purchase_transit_permit_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ecd_file_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transit_permit_file_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
