# Generated by Django 5.0.7 on 2026-10-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_rename_closed_stage_to_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ecd_file',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='ecd_file_original_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transit_permit_file',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transit_permit_file_original_name',
        ),
    ]
