# Generated by Django 5.2.8 on 2026-04-01 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0039_alter_purchaseitem_before_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_number', models.CharField(max_length=64, unique=True)),
                ('payment_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remark', models.TextField(blank=True, null=True)),
                ('purchase', models.ForeignKey(db_column='purchase_number', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='inventory.purchase', to_field='purchase_number')),
            ],
        ),
    ]
