# Generated by Django 5.2.8 on 2026-04-01 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_vendorpayment_approval_date_and_more'),
        ('inventory', '0039_alter_purchaseitem_before_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='vendorpayment',
            constraint=models.UniqueConstraint(fields=('purchase', 'installment_number'), name='uniq_vendor_payment_installment_per_purchase'),
        ),
    ]
