# Generated by Django 5.2.8 on 2026-04-01 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_vendorpayment_installment_number_and_more'),
        ('inventory', '0039_alter_purchaseitem_before_vat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_number', models.CharField(max_length=64, unique=True)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('payment_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status_remark', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_received_payments', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_received_payments', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_received_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_column='order_number', on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='inventory.order', to_field='order_number')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'installment_number'), name='uniq_received_payment_installment_per_order')],
            },
        ),
    ]
