# Generated by Django 5.2.8 on 2026-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_vendorpayment_freight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpayment',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
