# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_alter_vendorpayment_freight"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpayment",
            name="inland_transport",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
